const projectList = [
  {
    'id' : 0,
    'featured' : 'yes',
    'title' : 'CloudShare Hub',
    'headline' : 'Empowering Effortless File Sharing',
    'displa_img' : 'file-share/02.png',
    'images' : [
      'file-share/01.jpg',
      'file-share/02.png', 
      'file-share/03.png', 
      'file-share/04.png', 
      'file-share/05.png', 
      'file-share/06.png', 
    ],
    'links' : '/file-share-hub',
    'tags' : 'FullStack',
    'platform' : 'Web',
    'timeline' : 'December 2023',
    'role' : 'Software Engineer - Full Stack',
    'redirects' : [ { 'website': 'https://tubeguruji-file-share.vercel.app/', 'github': 'https://github.com/Ekpo-Emmanuel/Cloud-File-Share' } ],
    'technologies' : 'React (Next JS), Tailwind CSS, Firebase, Clerk, Google Cloud',
    'description' : 'lorem ipsum',
    'short_description': 'CloudShare Hub is an innovative and secure file-sharing platform built with cutting-edge technologies to provide users with a seamless and efficient way to share files. The platform harnesses the power of ReactJS and NextJS for a responsive and dynamic user interface, ensuring a smooth and engaging user experience.',
    'process': ''
  },
  {
    'id' : 1,
    'featured' : 'yes',
    'title' : 'Fitness Buddy',
    'headline' : 'Track and monitor your workouts',
    'displa_img' : 'fitness-app/01.png',
    'images' : [
      // 'fithub-WebApp/011.png', 
      // 'fithub-WebApp/02.png', 
      // 'fithub-WebApp/03.png', 
      // 'fithub-WebApp/04.png', 
      // 'fithub-WebApp/05.png', 
      // 'fithub-WebApp/06.png', 
      // 'fithub-WebApp/07.png', 
      // 'fithub-WebApp/08.png', 
      ],
    'links' : '/',
    'tags' : 'BackEnd FullStack',
    'platform' : 'App',
    'timeline' : '1 Month',
    'role' : 'Developer',
    'redirects' : [ { 'website': '/', 'github': 'https://github.com/Ekpo-Emmanuel/fitness-tracker-app' } ],
    'technologies' : 'React Native, Expo, GraphQL API, IBM StepZen, MongoDB',
    'description' : 'lorem ipsum',
    'short_description': 'The app is crafted with React Native for a consistent experience on iOS and Android, powered by Expo for efficient development. Utilizing GraphQL ensures flexible data fetching, and IBM StepZen orchestrates data seamlessly. MongoDB handles dynamic data requirements. This tech stack reflects our commitment to excellence, delivering a state-of-the-art fitness tracking solution.',
    'process': ""
  },
  {
    'id' : 2,
    'featured' : 'yes',
    'title' : 'Super School',
    'headline' : 'Revolutionizing School Administrative Processes with System',
    'displa_img' : 'school-ms/01.jpg',
    'images' : [
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg', 
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg',
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg',
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg',
    ],
    'links' : '/',
    'tags' : 'BackEnd FullStack',
    'platform' : 'Web',
    'timeline' : 'July 2023',
    'role' : 'Developer',
    'redirects' : [ { 'website': '/', 'github': 'https://github.com/Ekpo-Emmanuel/School_Management_System' } ],
    'technologies' : 'Javascript - JQuery, PHP, MySQL, Apache',
    'description' : 'Revolutionize School Administration and Learning with a Management System',
    'short_description': 'A comprehensive "School Management System" for educational institutions in Nigeria. Employing a full-stack approach using LAMP technologies, I created a responsive, scalable, and secure Management System. Tailored user interfaces for administrators, teachers, students, and parents facilitated seamless navigation and access to role-specific information. The CMS streamlined administrative tasks, enhancing efficiency in managing student records, timetables, attendance, and academic progress.',

    'process': ' <div className="features"> <p className="title">Features</p> <ul><li>Attendance Tracking: <span>real-time attendance tracking with  innovative system. Teachers can effortlessly mark attendance digitally, eliminating the need for paperwork and guaranteeing accurate and up-to-date records.</span></li> <li>Timetable Management <span>Effortlessly create and manage class schedules with our intuitive system. Customize timetables to accommodate diverse subjects, assign teachers, and allocate classrooms efficiently. Optimize your resource allocation for a streamlined and organized educational experience.</span></li> <li>Assignment and Grading <span> incorporates a robust grading feature that simplifies the assessment process. </span></li> <li>User Management: <span>Successfully implemented and managed user accounts for teachers, students, and parents, ensuring smooth onboarding and system access.</span></li><li>Communication Platform: <span>Established an efficient messaging platform, facilitating seamless communication among users for enhanced collaboration.</span></li> </ul> </div>'
  },
  {
    'id' : 3,
    'featured' : 'no',
    'title' : 'Exam-Sphere',
    'headline' : 'An exam scheduling platform for Alexander college students and teachers',
    'displa_img' : 'exam-sphere/01.png',
    'images' : [
      // 'exam-sphere/02.png'
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg', 
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg',
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg',
      // 'https://porfolio-prev44.000webhostapp.com/Ea%20Dev/assets/images/works/work-1/11.jpg',
    ],
    'links' : '/',
    'tags' : 'FullStack',
    'platform' : 'Web',
    'timeline' : 'Dec 2023 - Present',
    'role' : 'Developer, Designer',
    'redirects' : [ { 'website': '/', 'github': 'https://github.com/Ekpo-Emmanuel/exam-sphere' } ],
    'technologies' : 'Tailwind CSS,ReactJS, NodeJS, ExpressJS, RestAPI, Firebase, Superbase',
    'description' : 'lorem ipsum',
    'short_description': 'Exam Space is a web-based platform designed to simplify the process of exam scheduling for students. It addresses the challenges associated with traditional PDF-based schedules released by schools. The project is built using ReactJS for the frontend, NodeJS-Express for the backend and Superbase for database Management.',
    'process': '<div className="features"> <p className="title">Features</p> <ul><li>User-Friendly Interface: <span>Intuitive design for easy navigation and quick access to exam information.</span></li> <li>Calendar Integration: <span>Seamless integration with popular calendar applications (e.g., Google Calendar, Microsoft Outlook) for automatic synchronization of exam schedules.</span></li> <li>Real-Time Updates: <span>Users receive real-time notifications for any changes made to the exam schedule, ensuring they stay informed.</span></li> <li>Search and Filter Options:<span>Robust search and filter features enable users to quickly locate exams based on criteria like date, subject, or course.</span></li></ul> </div>'
  },
  {
    'id' : 4,
    'featured' : 'no',
    'title' : 'Fithub',
    'headline' : 'Fitness Website for Fitness Enthusiasts',
    'displa_img' : 'fithub-WebApp/011.png',
    'images' : [
      'fithub-WebApp/011.png', 
      'fithub-WebApp/02.png', 
      'fithub-WebApp/03.png', 
      'fithub-WebApp/04.png', 
      'fithub-WebApp/05.png', 
      'fithub-WebApp/06.png', 
      'fithub-WebApp/07.png', 
      'fithub-WebApp/08.png', 
      ],
    'links' : '/',
    'tags' : 'Website, FrontEnd',
    'platform' : 'Web',
    'timeline' : '1 Month',
    'role' : 'Developer',
    'redirects' : [ { 'website': 'https://fithub044.000webhostapp.com/', 'github': 'https://github.com/Ekpo-Emmanuel/Fithub/tree/main/Fithub' } ],
    'technologies' : 'JavaScript, PHP, API, HTML, CSS-Bootstrap',
    'description' : 'lorem ipsum',
    'short_description': 'The Landing Page is meticulously designed with a tech stack tailored to my preferences. JavaScript and PHP bring interactivity and server-side functionality, while APIs effortlessly connect and fetch data. The combination of HTML and CSS ensures a visually appealing and responsive design. This tech stack reflects my commitment to creating a personalized and engaging landing page for fitness enthusiasts.',
    'process': ' <div className="features"> <p className="title">Features</p> <ul><li>Intuitive User Interface: <span>Enjoy a modern and user-friendly interface, ensuring a seamless and visually engaging experience for users of all fitness levels.</span></li> <li>Goal Achievement Rewards: <span>Celebrate milestones and achievements with a built-in rewards system, motivating users to stay committed to their fitness objectives.</span></li> <li>Assignment and Grading <span> incorporates a robust grading feature that simplifies the assessment process. </span></li> <li>Interactive Progress Charts: <span>Visualize progress over time with interactive charts and graphs, allowing users to analyze trends and make informed adjustments to their fitness routines.</span></li><li>Communication Platform: <span>Established an efficient messaging platform, facilitating seamless communication among users for enhanced collaboration.</span></li> </ul> </div>'
  },
  {
    'id' : 5,
    'featured' : 'no',
    'title' : 'Melody Fusion',
    'headline' : 'Where Music, Technology, and Artistry Converge',
    'displa_img' : 'melody-fusion/01.jpg',
    'images' : [
      'melody-fusion/02.png', 
      'melody-fusion/03.png', 
      'melody-fusion/04.png', 
      'melody-fusion/05.png', 
    ],
    'links' : '/',
    'tags' : 'FullStack',
    'platform' : 'Web App',
    'timeline' : 'August 2023',
    'role' : 'Developer',
    'redirects' : [ { 'website': '/', 'github': 'https://github.com/Ekpo-Emmanuel/Music2' } ],
    'technologies' : 'Javascript, Superbase, PHP, API',
    'description' : 'lorem ipsum',
    'short_description': ' A dynamic and immersive music web app meticulously crafted using JavaScript. Immerse yourself in the world of melodies as it seamlessly blends the power of server-side processing with the interactivity of client-side scripting. Dive into a vast genre-spanning music library at your fingertips. With a sleek JavaScript interface, effortlessly explore playlists, artists, and albums.',
    'process': ""
  },
];

export default projectList;